apiVersion: v1
kind: ConfigMap
metadata:
  name: image-mirror
  namespace: openshift-cron-jobs
data:
  run: |-
    for mirror in $(ls /mirror/work/ -1); do /usr/bin/skopeo sync --all --src docker --src-creds $SRCCREDS --dest-creds $DSTCREDS --dest docker $(cat /mirror/work/${mirror}); done
