kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: image-mirroring
  namespace: openshift-cron-jobs
spec:
  schedule: 5 1 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: run
              configMap:
                name: image-mirror
                items:
                  - key: run
                    path: run
                defaultMode: 420
            - name: work
              configMap:
                name: image-mirror-list
                defaultMode: 420
          containers:
            - name: image-mirror
              image: 'quay.io/agileio/image-mirroring:latest'
              envFrom:
                - configMapRef:
                    name: image-mirror-env
              resources: {}
              volumeMounts:
                - name: run
                  mountPath: /mirror/config
                - name: work
                  mountPath: /mirror/work
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
